/// <reference types="anomaly-packer/types/game" />
/// <reference types="anomaly-packer/types/other" />
/// <reference types="anomaly-packer/types/addons/mcm" />

// This file has a top-level import, so it is a module. The ambient declarations live in
// `declare global` to stay visible to the scripts without importing them.
import type {} from "anomaly-packer"

declare global {
  type AddonId = "context_menu_icons"

  /**
   * Augments the empty `McmConfig` from anomaly-packer's mcm types, so
   * `ui_mcm.get('context_menu_icons/...')` is checked against the options that exist.
   */
  interface McmConfig {
    group_related_actions: boolean
    show_colored_icons: boolean
    show_separators: boolean
  }

  /** Globals exported by the sibling `context_menu_icons_mcm.script`. */
  namespace context_menu_icons_mcm {
    const defaultConfig: McmConfig
  }

  /**
   * A texture reference as written in `icons.ltx`. `CUITextureMaster::InitTexture` looks
   * the string up among the ids registered from `textures_desc` xml and, on a miss, falls
   * through to `CreateShader` with the string as a direct texture path — so a raw path
   * like `ui\ui_cmi_icons\use` resolves without any xml declaration.
   *
   * `UI.TextureId` is every id registered from `textures_descr` — vanilla's generated by
   * `gen-textures`, plus whatever an addon declares by merging into `UI.Textures` (this one
   * does so below). Strict on purpose: a mistyped id is otherwise a silently missing icon.
   */
  type IconTexture = UI.TextureId

  namespace UI {
    /**
     * The ids this addon registers itself, in `configs/ui/textures_descr/ui_cmi_icons.tsx`.
     * The `ui_cmi_*` set below is the addon's own sheet (`textures/ui/cmi_icons.dds`), named
     * for what each glyph depicts rather than for the action that happens to use it.
     */
    interface Textures {
      ui_cmi_battery: true
      ui_cmi_trashbin: true
      ui_cmi_boxes: true
      ui_cmi_hand: true
      ui_cmi_info: true
      ui_cmi_tools: true
      ui_cmi_bullets: true
      ui_cmi_gift: true
      ui_cmi_hammer: true
      ui_cmi_backpack: true
      ui_cmi_star: true
      ui_cmi_unstar: true
      ui_cmi_arrows: true
      ui_cmi_utensils: true
      ui_cmi_arrow_down: true
      ui_cmi_saw: true
      ui_cmi_divide: true
    }
  }

  /**
   * The stable ids of the built-in inventory context menu entries. These are exactly the
   * keys of `UIInventory.properties` (`ui_inventory.script:234`), which is what makes them
   * usable as icon keys at all.
   *
   * `custom_1..10` are intentionally absent: those slots are positional (slot 3 is whichever
   * addon registered third), so they carry no stable identity and are keyed on their
   * resolved `useN_functor` through `[functor_icons]` instead.
   */
  type PropertyId =
    | "use"
    | "attach_1"
    | "attach_2"
    | "attach_3"
    | "to_slot"
    | "to_ruck"
    | "move"
    | "move_all"
    | "donate"
    | "unload"

  /**
   * A `<script>.<function>` pair naming a `useN_functor` from an item's own ltx, used as
   * the icon key for the `custom_N` slots. Kept as a template type so a malformed key
   * (a bare script name, say) is a compile error.
   */
  type FunctorKey = `${string}.${string}`

  /**
   * `configs\plugins\context_menu_icons\icons.ltx`. Both sections are open-ended on
   * purpose: other addons extend them through DLTX (`mod_icons_<addon>.ltx`) with keys
   * this addon has never heard of, and a missing key simply means the row draws without
   * an icon.
   */
  interface ContextMenuIconsIni {
    /** Keyed on the `UIInventory.properties` key. */
    icons: Partial<Record<PropertyId, IconTexture>> &
      Record<string, IconTexture>
    /** Keyed on the resolved `useN_functor` of a `custom_N` slot. */
    functor_icons: Record<FunctorKey, IconTexture>
    /**
     * Keyed on the row's label — the raw translation id `InitProperties` collects, not the
     * translated text. This is the only key that varies with state: a row whose label
     * toggles ("mark as favourite" / "unmark") keeps one property id but changes its string
     * id, so it is the one place a toggled action can carry two icons.
     */
    label_icons: Record<string, IconTexture>
    /**
     * Which group a row belongs to, as a number. Rows are ordered by group, a separator is
     * drawn wherever the group changes, and rows within a group keep the game's own order.
     * Keys are resolved exactly like icons — label, then property id, then functor — so a
     * row is grouped by whichever of the three the config names.
     */
    groups: Record<string, number>
    /**
     * Text colour of a row as a hex value, `#rrggbb` or `#rrggbbaa`. Keyed like {@link icons}
     * — label, then property id, then functor — so any single row can be coloured. A row with
     * no entry keeps the game's own colour, which is what most of them should do.
     */
    colors: Record<string, `#${string}`>
  }

  interface IniFileSchemas {
    "plugins\\context_menu_icons\\icons.ltx": ContextMenuIconsIni
  }

  /**
   * This addon's own field on the context menu widget: the property keys of the menu
   * currently being filled, in row order. It is parked here for the duration of a
   * `FillList` because `AddItemToList` is handed only the row index.
   */
  interface UICellProperties {
    cmi_keys?: InventoryPropertyId[]
    /** Width of the icon column added to each row of the menu being filled. */
    cmi_column?: number
    /** The list box's original xml x, captured before this addon shifts it. */
    cmi_list_x?: number
    /**
     * The divider statics of the menu being filled. Their width is only known once every row
     * has been measured, so they are collected here and stretched afterwards.
     */
    cmi_dividers?: CUIStatic[]
    /**
     * Row indices of the dividers in the menu currently shown. Unlike the rest, this outlives
     * `FillList`: `Update` runs on every frame the menu is open and needs to know which rows
     * are not real entries.
     */
    cmi_divider_rows?: number[]
  }

  // --- Cross-script contracts (Anomaly's global-table convention) ---
  namespace context_menu_icons {
    const get_icon: typeof import("./scripts/index").get_icon
  }
}
