/// <reference types="anomaly-packer/types/game" />
/// <reference types="anomaly-packer/types/other" />
/// <reference types="anomaly-packer/types/addons/mcm" />
// Optional third-party integrations. These are type-only references — the globals they declare
// are guarded at runtime, so the addon runs unchanged for players without these mods installed.
/// <reference types="anomaly-packer/types/addons/item_ui_improvements" />
/// <reference types="anomaly-packer/types/addons/weapon_parts_overhaul" />

// This file has a top-level import, so it is a module. The ambient declarations live in
// `declare global` to stay visible to the scripts without importing them.
import type {} from "anomaly-packer"

declare global {
  type AddonId = "context_menu_overhaul"

  /** An item section id, re-exported as a global alias so the scripts can name it without importing. */
  type ItemSection = import("anomaly-packer").Section.Item

  /**
   * Augments the empty `McmConfig` from anomaly-packer's mcm types, so
   * `ui_mcm.get('context_menu_overhaul/...')` is checked against the options that exist.
   */
  interface McmConfig {
    group_related_actions: boolean
    use_colors: boolean
    show_separators: boolean
    details_shows_item_name: boolean
    capitalize_labels: boolean
    hide_gift: boolean
    field_strip_icons: boolean
    maintenance_icons: boolean
  }

  /** Globals exported by the sibling `context_menu_overhaul_utils.script`. */
  namespace context_menu_overhaul_utils {
    const vec: typeof import("./scripts/utils").vec
    const parse_hex: typeof import("./scripts/utils").parse_hex
    const capitalize: typeof import("./scripts/utils").capitalize
  }

  /** Globals exported by the sibling `context_menu_overhaul_mcm.script`. */
  namespace context_menu_overhaul_mcm {
    const defaultConfig: McmConfig
    const optionGroup: typeof import("./scripts/mcm").optionGroup
  }

  /**
   * A texture reference as written in `menu.ltx`. `CUITextureMaster::InitTexture` looks
   * the string up among the ids registered from `textures_desc` xml and, on a miss, falls
   * through to `CreateShader` with the string as a direct texture path — so a raw path
   * like `ui\ui_cmo_icons\use` resolves without any xml declaration.
   *
   * `UI.TextureId` is every id registered from `textures_descr` — vanilla's generated by
   * `gen-textures`, plus whatever an addon declares by merging into `UI.Textures` (this one
   * does so below). Strict on purpose: a mistyped id is otherwise a silently missing icon.
   */
  type IconTexture = UI.TextureId

  namespace UI {
    /**
     * The ids this addon registers itself, in `configs/ui/textures_descr/ui_cmo_icons.tsx`.
     * The `ui_cmo_*` set below is the addon's own sheet (`textures/ui/cmo_icons.dds`), named
     * for what each glyph depicts rather than for the action that happens to use it.
     */
    interface Textures {
      ui_cmo_placeholder: true
      ui_cmo_vest: true
      ui_cmo_cell: true
      ui_cmo_info: true
      ui_cmo_tools: true
      ui_cmo_bullets: true
      ui_cmo_gift: true
      ui_cmo_book: true
      ui_cmo_backpack: true
      ui_cmo_star: true
      ui_cmo_unstar: true
      ui_cmo_arrows: true
      ui_cmo_utensils: true
      ui_cmo_arrow_down: true
      ui_cmo_saw: true
      ui_cmo_divide: true
      ui_cmo_trashbin: true
      ui_cmo_untrashbin: true
      ui_cmo_helmet: true
      ui_cmo_silencer: true
      ui_cmo_gl: true
      ui_cmo_scope: true
      ui_cmo_patch: true
      ui_cmo_unpack: true
      ui_cmo_pie: true
      ui_cmo_screwdriver: true
      ui_cmo_components_star: true
      ui_cmo_oil: true
      ui_cmo_pda: true
      ui_cmo_magazine: true
      ui_cmo_health: true
      ui_cmo_water: true
      ui_cmo_hands: true
      ui_cmo_cigarette: true
      ui_cmo_lockpick: true
      ui_cmo_filter: true
      ui_cmo_plant: true
      ui_cmo_cross: true
      ui_cmo_tank: true
      ui_cmo_toolkit: true
      ui_cmo_merge: true
      ui_cmo_chevron: true
      // original game assets
      ui_cmo_battery: true
    }
  }

  /**
   * The stable ids of the built-in inventory context menu entries. These are exactly the
   * keys of `UIInventory.properties` (`ui_inventory.script:234`), which is what makes them
   * usable as icon keys at all.
   *
   * `custom_1..10` are intentionally absent: those slots are positional (slot 3 is whichever
   * addon registered third), so they carry no stable identity and are keyed on their
   * resolved `useN_functor` through `[functor_icons]` instead.
   */
  type PropertyId =
    | "use"
    | "attach_1"
    | "attach_2"
    | "attach_3"
    | "to_slot"
    | "to_ruck"
    | "move"
    | "move_all"
    | "donate"
    | "unload"

  /** A row key in the built menu: a real entry's property id, or the marker this addon inserts its dividers under, repeated from `DIVIDER` in `scripts/index.ts`. */
  type RowKey = InventoryPropertyId | "__cmo_divider" | "__cmo_unknown"

  /**
   * A `<script>.<function>` pair naming a `useN_functor` from an item's own ltx, used as
   * the icon key for the `custom_N` slots. Kept as a template type so a malformed key
   * (a bare script name, say) is a compile error.
   */
  type FunctorKey = `${string}.${string}`

  /**
   * `configs\plugins\context_menu_overhaul\menu.ltx`. Both sections are open-ended on
   * purpose: other addons extend them through DLTX (`mod_menu_<addon>.ltx`) with keys
   * this addon has never heard of, and a missing key simply means the row draws without
   * an icon.
   */
  interface ContextMenuIni {
    /** Keyed on the `UIInventory.properties` key. */
    icons: Partial<Record<PropertyId, IconTexture>> &
      Record<string, IconTexture>
    /** Keyed on the resolved `useN_functor` of a `custom_N` slot. */
    functor_icons: Record<FunctorKey, IconTexture>
    /**
     * Keyed on the row's label — the raw translation id `InitProperties` collects, not the
     * translated text. This is the only key that varies with state: a row whose label
     * toggles ("mark as favourite" / "unmark") keeps one property id but changes its string
     * id, so it is the one place a toggled action can carry two icons.
     */
    label_icons: Record<string, IconTexture>
    /**
     * Which group a row belongs to, as a number. Rows are ordered by group, a separator is
     * drawn wherever the group changes, and rows within a group keep the game's own order.
     * Keys are resolved exactly like icons — label, then property id, then functor — so a
     * row is grouped by whichever of the three the config names.
     */
    groups: { default: number } & Record<string, number>
    /**
     * Text colour of a row as a hex value, `#rrggbb` or `#rrggbbaa`. Keyed like {@link icons}
     * — label, then property id, then functor — so any single row can be coloured. A row with
     * no entry keeps the game's own colour, which is what most of them should do.
     */
    colors: Record<string, `#${string}`>
    /**
     * The glyph drawn at a row's right edge, marking a row that opens a further menu. Keyed like
     * {@link icons} — label, then property id, then functor. A row with an entry reserves a right
     * column and right-aligns the glyph; a row without keeps its plain layout.
     */
    chevrons: Record<string, IconTexture>
  }

  interface IniFileSchemas {
    "plugins\\context_menu_overhaul\\menu.ltx": ContextMenuIni
  }

  /**
   * This addon's own field on the context menu widget: the property keys of the menu
   * currently being filled, in row order. It is parked here for the duration of a
   * `FillList` because `AddItemToList` is handed only the row index.
   */
  interface UICellProperties {
    cmo_keys?: RowKey[]
    /** Raw translation ids of the rows being filled, kept because the drawn text may be rewritten while `[label_icons]` still keys on the id. */
    cmo_labels?: string[]
    /** Width of the icon column added to each row of the menu being filled. */
    cmo_column?: number
    /** Width of the right-hand chevron column, added to the menu when any row opens a further menu. */
    cmo_column_right?: number
    /** The chevron statics of the menu being filled, right-aligned once `W` is final since a row's right edge is only known then. */
    cmo_chevrons?: CUIStatic[]
    /** The list box's original xml x, captured before this addon shifts it. */
    cmo_list_x?: number
    /** The list box's original xml y, captured before the field strip moves it down under the icons, so the text menu can be put back. */
    cmo_list_y?: number
    /**
     * The divider statics of the menu being filled. Their width is only known once every row
     * has been measured, so they are collected here and stretched afterwards.
     */
    cmo_dividers?: CUIStatic[]
    /** Row indices of the dividers in the menu currently shown; outlives `FillList` because `Update` runs every frame and must not highlight a row that cannot be clicked. */
    cmo_inert_rows?: number[]
    /** Set while a field strip is filled as text, so `AddItemToList` routes through the main row builder for the field-strip icon and separators. */
    cmo_strip_text?: boolean
    /**
     * The cells of a horizontal icon strip (Weapon Parts Overhaul's field strip), one per part,
     * each an icon drawn into a single list item together with the part's click params. Set for
     * the life of the shown menu; absent for every ordinary vertical menu. A single item is used
     * so the scroll view has nothing to scroll — the strip must never move.
     */
    cmo_strip?: { item: UICellItem; params: CellPropertyParams }[]
    /** Pool of real inventory cells reused across openings so the strip never leaks statics onto the form. */
    cmo_pool?: UICellItem[]
    /** The strip's "remove all" list row and its form-space rect, kept so `Update`'s highlight can be placed despite the list box's downward offset. */
    cmo_row?: { item: CUIListBoxItem; x: number; y: number; w: number; h: number }
    /** The game's own item-info window, created once and driven by section on hover for the strip's tooltip. */
    cmo_info?: UIInfoItem
    /** The functor the subclass dispatches a click through — Weapon Parts Overhaul's `act_fieldstrip`; read to route a strip-cell click to the part under the cursor. */
    functor?: (this: void, ...args: unknown[]) => unknown
    /** Set while a field strip is registered with `Register_UI`, so it is unregistered exactly once on close. */
    cmo_registered?: boolean
    /** The subclass's own `OnKeyboard`, captured so the strip override falls back to it for every non-strip key and menu. */
    cmo_orig_keyboard?: (this: UICellProperties, dik: number, action: number) => boolean
    /** The subclass's own `OnHide`, captured so the strip override can drop its UI registration before the class hides. */
    cmo_orig_hide?: (this: UICellProperties) => void
  }

  // --- Cross-script contracts (Anomaly's global-table convention) ---
  namespace context_menu_overhaul {
    const get_icon: typeof import("./scripts/index").get_icon
    const settings: typeof import("./scripts/index").settings
    const row_label: typeof import("./scripts/index").row_label
    const finish_layout: typeof import("./scripts/index").finish_layout
    const reserve_column: typeof import("./scripts/index").reserve_column
    const draw_icon: typeof import("./scripts/index").draw_icon
    const draw_divider: typeof import("./scripts/index").draw_divider
    const vanilla_fill_list: typeof import("./scripts/index").vanilla_fill_list
    const vanilla_add_item: typeof import("./scripts/index").vanilla_add_item
    const safe_index: typeof import("./scripts/index").safe_index
    const UNKNOWN: typeof import("./scripts/index").UNKNOWN
    const DIVIDER: typeof import("./scripts/index").DIVIDER
    const DIVIDER_LINE_H: typeof import("./scripts/index").DIVIDER_LINE_H
  }

  /** The Weapon Parts Overhaul field strip, in `context_menu_overhaul_wpo.script`; called by the shared hooks in `index`. */
  namespace context_menu_overhaul_wpo {
    const is_field_strip: typeof import("./scripts/wpo").is_field_strip
    const is_maintenance: typeof import("./scripts/wpo").is_maintenance
    const fill_icons: typeof import("./scripts/wpo").fill_icons
    const fill_text: typeof import("./scripts/wpo").fill_text
    const clear: typeof import("./scripts/wpo").clear
    const highlight: typeof import("./scripts/wpo").highlight
    const patch: typeof import("./scripts/wpo").patch
  }
}
