import type { FileExtension, Texts } from "anomaly-packer"

export const extension: FileExtension = "ltx"

const icon = {
  placeholder: "ui_cmo_placeholder",
  trashbin: "ui_cmo_trashbin",
  untrashbin: "ui_cmo_untrashbin",
  vest: "ui_cmo_vest",
  helmet: "ui_cmo_helmet",
  silencer: "ui_cmo_silencer",
  gl: "ui_cmo_gl",
  scope: "ui_cmo_scope",
  patch: "ui_cmo_patch",
  unpack: "ui_cmo_unpack",
  cell: "ui_cmo_cell",
  info: "ui_cmo_info",
  tools: "ui_cmo_tools",
  book: "ui_cmo_book",
  bullets: "ui_cmo_bullets",
  gift: "ui_cmo_gift",
  backpack: "ui_cmo_backpack",
  star: "ui_cmo_star",
  unstar: "ui_cmo_unstar",
  arrows: "ui_cmo_arrows",
  utensils: "ui_cmo_utensils",
  arrow_down: "ui_cmo_arrow_down",
  saw: "ui_cmo_saw",
  divide: "ui_cmo_divide",
  pie: "ui_cmo_pie",
  components: "ui_cmo_screwdriver",
  components_star: "ui_cmo_components_star",
  oil: "ui_cmo_oil",
  pda: "ui_cmo_pda",
  magazine: "ui_cmo_magazine",
  health: "ui_cmo_health",
  water: "ui_cmo_water",
  hands: "ui_cmo_hands",
  cigarette: "ui_cmo_cigarette",
  battery: "ui_cmo_battery",
  lockpick: "ui_cmo_lockpick",
  filter: "ui_cmo_filter",
  plant: "ui_cmo_plant",
  cross: "ui_cmo_cross",
  stash: "ui_inGame2_PDA_icon_backpackstash",
  mark: "ui_icons_newPDA_mark_e",
} as const satisfies Record<string, UI.TextureId>

export default (t: Texts) => {
  const f = t.forFile<ContextMenuIni>()
  return [
    f.ltx({
      section: "icons",
      entries: {
        use: icon.hands,
        "use@food": icon.utensils,
        "use@drink": icon.water,
        "use@medkit": icon.health,
        "use@smoke": icon.cigarette,
        attach_1: icon.scope,
        attach_2: icon.scope,
        attach_3: icon.scope,
        "attach_1@sil": icon.silencer,
        "attach_2@sil": icon.silencer,
        "attach_3@sil": icon.silencer,
        "attach_1@scope": icon.scope,
        "attach_2@scope": icon.scope,
        "attach_3@scope": icon.scope,
        "attach_1@gl": icon.gl,
        "attach_2@gl": icon.gl,
        "attach_3@gl": icon.gl,
        to_slot: icon.cell,
        "to_slot@outfit": icon.vest,
        "to_slot@helmet": icon.helmet,
        "to_slot@backpack": icon.backpack,
        to_ruck: icon.backpack,
        "to_ruck@outfit": icon.vest,
        "to_ruck@helmet": icon.helmet,
        "to_ruck@backpack": icon.backpack,
        move: icon.arrows,
        move_all: icon.arrows,
        donate: icon.gift,
        unload: icon.bullets,
        detach_silencer: icon.silencer,
        detach_scope: icon.scope,
        detach_gl: icon.gl,
        drop: icon.arrow_down,
        drop_all: icon.arrow_down,
        DYN_FUNC_SP_fav: icon.star,
        DYN_FUNC_SP_junk: icon.trashbin,
      },
    }),
    f.ltx({
      section: "functor_icons",
      entries: {
        "item_parts.menu_disassembly": icon.saw,
        "bind_item.menu_separate": icon.divide,
        "ui_itm_details.menu_details": icon.info,
        "item_backpack.menu_stash": icon.stash,
        "item_repair.menu_tool": icon.tools,
        "item_recipe.menu_read": icon.book,
        "item_device.menu_battery": icon.battery,
        "ui_pda_npc_tab.menu_view": icon.pda,
        "itms_manager.menu_unpack": icon.unpack,
        "itms_manager.menu_open": icon.unpack,
        "bind_container.access_inventory": icon.unpack,
        "item_weapon.menu_scope_inv": icon.scope,
        "itms_manager.menu_place": icon.mark,
        "item_tent.str_use": icon.mark,
        "gameplay_disguise.menu_patch": icon.patch,
        "mag_pouches.precond_install": icon.magazine,
        "speed_loaders.precond_install": icon.magazine,
        "speed_loaders.precond_install_shotgun": icon.magazine,
        "speed_loaders.precond_install_rifle": icon.magazine,
        "placeable_furniture.place_item": icon.plant,
      },
    }),
    f.ltx({
      section: "label_icons",
      entries: {
        st_rax_fav: icon.star,
        st_rax_unfav: icon.unstar,
        st_rax_junk: icon.trashbin,
        st_rax_unjunk: icon.untrashbin,
        st_batch_breakdown: icon.saw,
        ui_haru_add_item_to_qaw: icon.pie,
        st_field_strip: icon.components,
        st_wpo_replace_parts: icon.oil,
        st_favorite_parts: icon.components_star,
        st_mag_eject_magazine: icon.magazine,
        st_mag_unload_ammo: icon.magazine,
        st_mag_loadout_add: icon.magazine,
        st_mag_loadout_remove: icon.magazine,
        st_mag_retool: icon.magazine,
        st_remove_pouch: icon.magazine,
        st_remove_speed_loader: icon.magazine,
        st_filter_equip: icon.filter,
        st_remove_filter: icon.filter,
        st_tank_equip: icon.placeholder,
        st_tank_remove: icon.placeholder,
        st_unlock_pick: icon.lockpick,
        cb_pda_cancel: icon.cross,
      },
    }),
    f.ltx({
      section: "groups",
      entries: {
        "ui_itm_details.menu_details": 1,
        default: 2,
        DYN_FUNC_SP_fav: 3,
        DYN_FUNC_SP_junk: 3,
        drop: 4,
        drop_all: 4,
        "item_parts.menu_disassembly": 5,
        st_batch_breakdown: 5,
      },
    }),
    f.ltx({
      section: "colors",
      entries: {
        drop: "#888888",
        drop_all: "#888888",
        "item_parts.menu_disassembly": "#888888",
        st_batch_breakdown: "#888888",
        st_rax_fav: "#dec983",
        st_rax_unfav: "#dec983",
        st_rax_junk: "#888888",
        st_rax_unjunk: "#888888",
      },
    }),
  ]
}
